### ISSUE TITLE
soft brick (or bootloop?) on i9100

### ISSUE THREAD

**Issue by dzervas** [crondog/i9300-archlinux-initramfs#1]
I followed your steps and I generated the ramdisk.img in my arch chroot and the I mkbootimg from the android bash (I have an i9100)
I flashed the boot.img with mobile odin and then I got stuck in the sgs2 logo. I had to flash recovery with heimdal (is that a boot loop or a soft brick?) to be able to reflash my previous kernel (siyah)

**Comment by crondog** [comment]
Ok well it could be a couple of things. If you didnt modify the init file then you will see on line 54, that code will give a boot loop. Try without your sdcard. If it boots android then its that code. If not then i am not sure since i dont have a i9100.

I havent worked on this for a while since i have gone back to uni. I think there is a problem with switch_root but i am not sure what it is...

**Comment by dzervas** [comment]
back to uni?
is there any way that I can flash the boot.img to the second ROM? (siyah
kernel dual booting)
On Jul 31, 2012 11:30 AM, "crondog" <
reply@reply.github.com>
wrote:

**Comment by crondog** [comment]
University ;)

From what i can gather http://forum.xda-developers.com/showthread.php?t=1680851 Siyahs kernel uses one kernel for 2 different roms. This is similar to what i am doing.

**Comment by dzervas** [comment]
:-P
yes, well how can I flash the boot.img to second rom? should I ask Gkoham
Moral?
On Jul 31, 2012 11:50 AM, "crondog" <
reply@reply.github.com>
wrote:

**Comment by crondog** [comment]
You dont.

With mine the boot.img contain the android kernel. Then when the init script is loaded it will just boot normally if no sdcard is inserted. If there is a sdcard inserted then it tries to change the root filesystem the the one on the sdcard.

With Siyah's the boot.img has the android kernel too. However if you read that article it explains that the second rom's system is on a hidden partition. When booting it needs to copy the second rom to the first rom or the first rom to the second rom and then boot normally.

So essentially both mine and his have 1 boot.img. Mine tries to switch_root to the new system and his moves the entire rom around.
